spring:
  rabbitmq:
    host: 192.168.52.132
    port: 5672
    username: admin
    password: admin
  application:
    name: item-service
server:  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka